[book]
title = "The Plumb Book"
authors = ["Aram Hammoudeh"]
language = "en"
src = "docs/src"

[build]
build-dir = "book"
create-missing = false

[output.html]
edit-url-template = "https://github.com/aram-devdocs/plumb/edit/main/{path}"
git-repository-url = "https://github.com/aram-devdocs/plumb"
site-url = "/"
cname = "plumb.aramhammoudeh.com"

[output.html.fold]
enable = true
level = 1

[output.html.search]
enable = true
limit-results = 20
