//! # plumb-mcp
//!
//! Model Context Protocol server for Plumb, backed by the official
//! [`rmcp`] Rust SDK.
//!
//! The server exposes two tools to AI coding agents:
//!
//! - `echo` — smoke-tests the transport.
//! - `lint_url` — lints a URL and returns violations in the MCP-compact
//!   shape from `docs/local/prd.md` §14.2. Walking-skeleton accepts
//!   `plumb-fake://` URLs only.
//!
//! The [`PlumbServer`] type implements [`rmcp::ServerHandler`] via the
//! `#[tool_router]` / `#[tool_handler]` macros. Extend it by adding new
//! `#[tool]` methods; see `.agents/rules/mcp-tool-patterns.md`.
//!
//! [`rmcp`]: https://crates.io/crates/rmcp

#![forbid(unsafe_code)]
#![deny(clippy::unwrap_used, clippy::expect_used)]

use std::io;

use plumb_core::{Config, PlumbSnapshot, run};
use plumb_format::mcp_compact;
use rmcp::{
    ServerHandler, ServiceExt,
    handler::server::{router::tool::ToolRouter, tool::Parameters},
    model::{
        CallToolResult, Content, ErrorData, Implementation, ProtocolVersion, ServerCapabilities,
        ServerInfo,
    },
    tool, tool_handler, tool_router,
    transport::stdio,
};
use schemars::JsonSchema;
use serde::Deserialize;
use thiserror::Error;

/// MCP server errors.
#[derive(Debug, Error)]
#[non_exhaustive]
pub enum McpError {
    /// Underlying I/O error on stdin/stdout.
    #[error("mcp i/o: {0}")]
    Io(#[from] io::Error),
    /// rmcp service or transport failure.
    #[error("mcp service: {0}")]
    Service(String),
}

/// Arguments to the `echo` tool.
#[derive(Debug, Deserialize, JsonSchema)]
pub struct EchoArgs {
    /// Message to echo back.
    pub message: String,
}

/// Arguments to the `lint_url` tool.
#[derive(Debug, Deserialize, JsonSchema)]
pub struct LintUrlArgs {
    /// URL to lint. Walking-skeleton accepts `plumb-fake://` URLs only.
    pub url: String,
}

/// The Plumb MCP server. Cheap to construct.
#[derive(Clone)]
pub struct PlumbServer {
    tool_router: ToolRouter<Self>,
}

impl Default for PlumbServer {
    fn default() -> Self {
        Self::new()
    }
}

// rmcp's `#[tool_router]`/`#[tool]` macros synthesize helper associated
// functions that can't receive doc comments. The macros themselves carry
// the description — and it ships in the MCP `tools/list` response, which
// is the actual docs surface agents consume.
#[allow(missing_docs)]
#[tool_router]
impl PlumbServer {
    /// Construct a new server. The tool registry is generated by the
    /// `#[tool_router]` macro from the `#[tool]`-annotated methods below.
    #[must_use]
    pub fn new() -> Self {
        Self {
            tool_router: Self::tool_router(),
        }
    }

    /// Echo a message — smoke test for the MCP transport.
    #[tool(description = "Echo a message — smoke test the MCP transport.")]
    async fn echo(
        &self,
        Parameters(args): Parameters<EchoArgs>,
    ) -> Result<CallToolResult, ErrorData> {
        Ok(CallToolResult::success(vec![Content::text(args.message)]))
    }

    /// Lint a URL with Plumb. Walking-skeleton accepts `plumb-fake://`
    /// URLs only; real URLs require the Chromium driver (PR #2).
    #[tool(
        description = "Lint a URL with Plumb. Walking-skeleton accepts plumb-fake:// URLs only."
    )]
    async fn lint_url(
        &self,
        Parameters(args): Parameters<LintUrlArgs>,
    ) -> Result<CallToolResult, ErrorData> {
        if !args.url.starts_with("plumb-fake://") {
            return Ok(CallToolResult::success(vec![Content::text(
                "lint_url currently only accepts plumb-fake:// URLs in the walking skeleton.",
            )]));
        }
        let snapshot = PlumbSnapshot::canned();
        let config = Config::default();
        let violations = run(&snapshot, &config);
        let (text, structured) = mcp_compact(&violations);
        // rmcp 0.2 CallToolResult carries text/image/resource content
        // directly. Ship the structured JSON as an additional text block;
        // agents that want strict JSON parse the second block.
        let structured_text = serde_json::to_string(&structured).unwrap_or_default();
        Ok(CallToolResult::success(vec![
            Content::text(text),
            Content::text(structured_text),
        ]))
    }
}

#[tool_handler]
impl ServerHandler for PlumbServer {
    fn get_info(&self) -> ServerInfo {
        ServerInfo {
            protocol_version: ProtocolVersion::V_2024_11_05,
            capabilities: ServerCapabilities::builder().enable_tools().build(),
            server_info: Implementation {
                name: "plumb".into(),
                version: env!("CARGO_PKG_VERSION").into(),
            },
            instructions: Some(
                "Deterministic design-system linter. Call `lint_url` with a URL to get violations; \
                 use `echo` to smoke-test the transport."
                    .into(),
            ),
        }
    }
}

/// Run the MCP server on stdin/stdout until EOF.
///
/// # Errors
///
/// Returns [`McpError::Service`] if rmcp's service loop fails or [`McpError::Io`]
/// on transport errors.
pub async fn run_stdio() -> Result<(), McpError> {
    let handler = PlumbServer::new();
    let service = handler
        .serve(stdio())
        .await
        .map_err(|e| McpError::Service(e.to_string()))?;
    service
        .waiting()
        .await
        .map_err(|e| McpError::Service(e.to_string()))?;
    Ok(())
}
